### PR TITLE
Added a volatile option for DualCache

### PR DESCRIPTION
**Pull request by iagocanalejas**
Hi i have implemented a volatile option for your cache with some extra tests to check if it works. I think it does not include a big load for your library please check the changes and if it can be included in the library.

Btw nice job with your work.

### CODE REVIEW

**Comment by iagocanalejas** [comment]
Sorry i mess up code style didn't see the checkstyle configuration

**Comment by vincentbrison** [comment]
Hi,

Thats a great addition but I do not think it is the job of the library to manage this behavior. The cache is dedicated to store and retrieve in a efficient way cached value. Using a volatile option is way to mange those entries which can be performed by a dedicated object, for exemple by using the [decorator pattern](https://en.wikipedia.org/wiki/Decorator_pattern).

The usage your are describing is probably needed by one of your application but not needed is the general case. For exemple, I use my cache in an application where each entry has a different lifetime. This feature wont go fine alongside your general volatile option. The issue occures because we want to give more responsability to a single object.

So I prefer to not merge your MR, even if its quality is fine. However if you really need this feature in this way, feel free to use [JitPack](https://jitpack.io/) to use your own implementation directly from GitHub.

I am staying open to discuss about this.

Best regards.

**Comment by iagocanalejas** [comment]
Yeah i need this behaviour to my app and i though it could be a good addition for the library to give the option to implement this "natively" as many caches do. Also, with a little modification to my PR, this can be used to handle different lifetimes.

But i get your point so with your permission i will fork your library into JitPack to use it.

Nice job with the library btw and thanks for take a look into the PR.

**Comment by vincentbrison** [comment]
Thanks !
You have full permission according to the licence to fork it and adapt it to your needs, thanks open source philosophy (: .

**Pull request closed without merging**
